name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'version.py'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'version.py'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check version change
      run: |
        # 获取最新提交和上一次提交的version.py内容
        CURRENT_VERSION=$(grep 'APP_VERSION' version.py | cut -d\' -f2)
        PREVIOUS_VERSION=$(git show HEAD^:version.py 2>/dev/null | grep 'APP_VERSION' | cut -d\' -f2 || echo "")
        
        # 比较版本号是否变化
        if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
          echo "::set-output name=changed::true"
          echo "Version changed from $PREVIOUS_VERSION to $CURRENT_VERSION"
        else
          echo "::set-output name=changed::false"
          echo "Version not changed ($CURRENT_VERSION)"
        fi
        
    # 只有版本号变化时才构建
    - name: Build the Docker image
      if: steps.check_version.outputs.changed == 'true'
      run: |
        cd docker
        docker build . --file Dockerfile --tag nastool:${{ steps.check_version.outputs.current_version }}



        
