name: NssTool Image 构建

on:
  workflow_dispatch:
    inputs:
      version_suffix:
        description: 'Optional version suffix (e.g., "beta")'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Extract Version
        id: version
        run: |
          app_version=$(cat version.py | sed -ne "s/APP_VERSION\s=\s'v\(.*\)'/\1/gp")
          if [ -n "${{ inputs.version_suffix }}" ]; then
            app_version="${app_version}-${{ inputs.version_suffix }}"
          fi
            echo "app_version=${app_version}" >> $GITHUB_ENV
            echo "image_name=ghcr.io/${{ github.repository_owner }}/nas-tools:${app_version}-debian" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v2
          
      - name: Set Up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: docker
          file: docker/debian.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.image_name }}
          labels: |
            org.opencontainers.image.source=${{ github.repository_url }}
